### PR TITLE
add devise model, cancel out registerable in model,

### PR DESCRIPTION
**Pull request by Kwasi008**
@jrmcgarvey @micronix 

Hi John so I remove the register-able from the model which removed the routing, and also canceled the views on how to register, please let me know what you think.

Thank you

### CODE REVIEW

**Review by jrmcgarvey — CHANGES_REQUESTED** [review]
Untested code, not ready for merge.

**Review by jrmcgarvey — CHANGES_REQUESTED** [review]
There is a small merge conflict that must be addressed before this code can be merged.

**Comment by Kwasi008** [comment]
Hi John I fixed the merge conflicts and everything works. Please let me know what you think.

@jrmcgarvey

**Review by jrmcgarvey — APPROVED** [review]
Ok, approved

**Pull request merged**
